Portfolio/ViewModels/Realisations/DisplayViewModel.cs
using System.Collections.Generic;

using ObjectModel.Competences;
using ObjectModel.Realisations;

namespace Portfolio.ViewModels.Realisations
{
    /// <summary>
    /// ViewModel used to display one realisation in detail.
    /// </summary>
    public class DisplayViewModel
    {
        public int RealisationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        public IEnumerable<Competence> LinkedCompetences { get; set; }

        public DisplayViewModel() { }

        public DisplayViewModel(Realisation instance)
        {
            this.RealisationId = instance.Id;
            this.Name = instance.Name;
            this.Description = instance.Description;
            this.ImageName = instance.ImageName;

            this.LinkedCompetences = new List<Competence>();
        }
    }
}

Portfolio/ViewModels/Realisations/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ObjectModel.Realisations;

namespace Portfolio.ViewModels.Realisations
{
    using System.Web.Mvc;

    /// <summary>
    /// ViewModel used to display a list of realisations (not in detail)
    /// </summary>
    public class ListViewModel
    {
        public IEnumerable<Realisation> Realisations { get; set; }
        public IEnumerable<SelectListItem> RealisationTypesItems { get; set; }

        public ListViewModel(IEnumerable<Realisation> instance, IEnumerable<RealisationType> realisationTypes)
        {
            this.Realisations = instance;
            this.RealisationTypesItems = EnumsToSelectListItems(realisationTypes);
        }

        private IEnumerable<SelectListItem> EnumsToSelectListItems(IEnumerable<RealisationType> enumValues)
        {
            var selectList = enumValues.Select(enumValue => new SelectListItem { Text = enumValue.ToString(), Value = ((int)enumValue).ToString() }).ToList();
            selectList.Add( new SelectListItem { Text = "All", Value = "-1" });
            return selectList.OrderBy(p => Int32.Parse(p.Value));
        }
    }
}

Portfolio/Controllers/CompetenceController.cs
using System.Web.Mvc;

using ObjectModel.Database;
using ObjectModel.Repositories;
using ObjectModel.Services;

using Portfolio.ViewModels.Competences;

namespace Portfolio.Controllers
{
    public class CompetenceController : BaseController
    {
        private RealisationAndCompetenceService _realAndCompService;

        public CompetenceController()
        {
            this._realAndCompService = new RealisationAndCompetenceService(new SMEntityRepository<ObjectModel.Database.Realisation, ObjectModel.Realisations.Realisation>(new SMPortfolioEntities()), new SMEntityRepository<ObjectModel.Database.Competence, ObjectModel.Competences.Competence>(new SMPortfolioEntities()));
        }

        public ActionResult Index()
        {
            var competenceList = _realAndCompService.GetAllCompetences();
            var model = new ListViewModel(competenceList);
            return View("Index", model);    
        }

        public ActionResult Detail(int id)
        {
            var competence = _realAndCompService.GetCompetenceById(id);

            if (competence == null)
                return View("404");

            var model = new DisplayViewModel(competence);
            model.LinkedRealisations = _realAndCompService.GetLinkedRealisations(competence.Id);

            return View("Detail", model);
        }
    }
}

Portfolio/Controllers/RealisationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ObjectModel.Services;
using ObjectModel.Repositories;
using ObjectModel.Database;

using Portfolio.ViewModels.Realisations;

namespace Portfolio.Controllers
{
    public class RealisationController : BaseController
    {
        private RealisationAndCompetenceService _realAndCompService;

        public RealisationController()
        {
            this._realAndCompService = new RealisationAndCompetenceService(new SMEntityRepository<ObjectModel.Database.Realisation, ObjectModel.Realisations.Realisation>(new SMPortfolioEntities()), new SMEntityRepository<ObjectModel.Database.Competence, ObjectModel.Competences.Competence>(new SMPortfolioEntities()));
        }

        public ActionResult Index()
        {
            var realisationList = _realAndCompService.GetAllRealisations();
            var model = new ListViewModel(realisationList);
            return View("Index", model);  
        }

        public ActionResult Detail(int id)
        {
            var realisation = _realAndCompService.GetRealisationById(id);

            if (realisation == null)
                return View("404");

            var model = new DisplayViewModel(realisation);
            model.LinkedCompetences = _realAndCompService.GetLinkedCompetences(realisation.Id);

            return View("Detail", model);
        }
    }
}

Portfolio/Views/Realisation/Detail.cshtml
@{
    ViewBag.Title = "RealisationDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Portfolio.ViewModels.Realisations.DisplayViewModel
<h2>@Model.Name</h2>

<div class ="realisation-description">@Html.Raw(Model.Description)</div>
<img src="~/Content/img/logos/@Model.ImageName" class="realisation-logo" />

<div class="realisation-detail">
    <span>Les compétences que j'ai pu mettre en pratique lors de ce projet :</span>
    @if (Model.LinkedCompetences.Any(c => c.Type == ObjectModel.Competences.CompetenceType.TechnicalCompetence))
    {
        
        <div class="competenceblock">
            Compétences techniques :
            <ul>
                @foreach (var comp in Model.LinkedCompetences.Where(c => c.Type == ObjectModel.Competences.CompetenceType.TechnicalCompetence).OrderBy(p => p.Name))
                {
                    <li>@Html.ActionLink(comp.Name, "Detail", "Competence", new { id = comp.Id }, null)</li>
                }
            </ul>
        </div>
    }
    
    @if (Model.LinkedCompetences.Any(c => c.Type == ObjectModel.Competences.CompetenceType.HumanCompetence))
    {
        <div class="competenceblock">
            Compétences humaines :
            <ul>
                @foreach (var comp in Model.LinkedCompetences.Where(c => c.Type == ObjectModel.Competences.CompetenceType.HumanCompetence).OrderBy(p => p.Name))
                {

                    <li>@Html.ActionLink(comp.Name, "Detail", "Competence", new { id = comp.Id }, null)</li>
                }
            </ul>
        </div>
    }
</div>



Portfolio/Views/Realisation/Index.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ObjectModel.Helpers
@using ObjectModel.Realisations
@model Portfolio.ViewModels.Realisations.ListViewModel

<h2>Mes réalisations</h2>

@foreach (RealisationType realisationType in Enum.GetValues(typeof(RealisationType)))
{
    <h3>@EnumHelpers.GetResourceText(realisationType)</h3>
    foreach (var real in Model.Realisations.Where(p => p.Type == realisationType))
    {
        <div class="realisation-summary">
            <img src="~/Content/img/logos/@real.ImageName" />
            <div>
                <span class="realisationName">@real.Name</span> @real.ShortDescription
                @Html.ActionLink(ObjectModel.Helpers.ResourceHelpers.GetString("General", "SEE_MORE"), "Detail", new { id = real.Id })
            </div>
        </div>
    }
}
