Portfolio/ViewModels/Layout/NavBarViewModel.cs
using ObjectModel;

using System.Collections.Generic;

namespace Portfolio.ViewModels.Layout
{
    public class NavBarViewModel
    {
        public Dictionary<NavigationBarItem, string> NavItems { get; set; }

        public string CurrentController { get; set; }

        public NavigationBarItem ActiveTab { get; set; }
        
        public NavBarViewModel(Dictionary<NavigationBarItem, string> navItems, NavigationBarItem activeTab)
        {
            NavItems = navItems;
            ActiveTab = activeTab;
        }
    }
}

Portfolio/Controllers/LayoutController.cs
using ObjectModel;
using ObjectModel.Helpers;
using Portfolio.ViewModels.Layout;

using System.Web.Mvc;

namespace Portfolio.Controllers
{
    using System;
    using System.Collections.Generic;

    public class LayoutController : BaseController
    {
        public ActionResult NavigationBar(Dictionary<string,string> activeTabInfo)
        {
            var activeTab = this.GetActiveNavBarItem(activeTabInfo["controller"], activeTabInfo["action"]);
            var model = new NavBarViewModel(EnumHelpers.GetAllElementsWithResourceKey<NavigationBarItem>(), activeTab);

            return View("_Navbar", model);
        }

        public void ChangeLanguage(string id)
        {
            CreateCookie("Language", id);
            Response.Redirect(Request.UrlReferrer.ToString());
        }

        private NavigationBarItem GetActiveNavBarItem(string controller, string action)
        {
            switch (controller)
            {
                case "Home":
                    return action == "Contact" ? NavigationBarItem.Contact : NavigationBarItem.Home;
                case "Realisation":
                    return NavigationBarItem.Realisations;
                case "Competence":
                    return NavigationBarItem.Competences;
            }
            throw new NotSupportedException("Action must exist");
        }
    }
}

Portfolio/Views/Shared/404.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Le lien que vous avez tapé semble incorrect ou la page que vous souhaitez consulter a été supprimée.</h4>

Portfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Mon portfolio</title>
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/portfolio.css" rel="stylesheet">
    <link rel="SHORTCUT ICON" href="~/Content/img/favicon.ico">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400' rel='stylesheet' type='text/css'>
    
    <script src="@Url.Content("~/Scripts/jquery/jquery-2.1.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Highcharts-4.0.1/js/highcharts-all.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/bootstrap/js/bootstrap.min.js")" type="text/javascript"></script>
</head>
<body>
    <!-- Header -->
    @Html.Action("NavigationBar", "Layout", new { activeTabInfo = ViewBag.ActiveTabInfo })

    <!-- Body -->
    <div class ="content">
        @RenderBody()
    </div>

    <!-- Footer -->
    <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
        <div class="container">
            Copyright Stéphane Miginiac - 2014
            <div class="image-bar">
                <a href="@Url.Action("ChangeLanguage", "Layout", new { id = "fr-FR" })"><img src="~/Content/img/flags/france.png" title="Voir ce site en français" /></a>
                <a href="@Url.Action("ChangeLanguage", "Layout", new { id = "en-GB" })"><img src="~/Content/img/flags/english.png" title="See this website in english" /></a>
            </div>
        </div>
    </nav>
</body>
</html>

Portfolio/Views/Shared/_Navbar.cshtml
@model Portfolio.ViewModels.Layout.NavBarViewModel

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div> 
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                @{ string active = Model.ActiveTab == NavigationBarItem.Home ? "active" : string.Empty;}
                <li class="@active">@Html.ActionLink(ObjectModel.Helpers.ResourceHelpers.GetString("General", Model.NavItems[NavigationBarItem.Home]), "Index", "Home")</li>
                @{ active = Model.ActiveTab == NavigationBarItem.Competences ? "active" : string.Empty;}
                <li class="@active">@Html.ActionLink(ObjectModel.Helpers.ResourceHelpers.GetString("General", Model.NavItems[NavigationBarItem.Competences]), "Index", "Competence")</li>
                @{ active = Model.ActiveTab == NavigationBarItem.Realisations ? "active" : string.Empty;}
                <li class="@active">@Html.ActionLink(ObjectModel.Helpers.ResourceHelpers.GetString("General", Model.NavItems[NavigationBarItem.Realisations]), "Index", "Realisation")</li>
                @{ active = Model.ActiveTab == NavigationBarItem.Contact ? "active" : string.Empty;}
                <li class="@active">@Html.ActionLink(ObjectModel.Helpers.ResourceHelpers.GetString("General", Model.NavItems[NavigationBarItem.Contact]), "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</nav>
