Portfolio/ViewModels/Competences/DisplayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ObjectModel.Competences;
using ObjectModel.Realisations;

namespace Portfolio.ViewModels.Competences
{
    /// <summary>
    /// ViewModel used to display in detail one competence
    /// </summary>
    public class DisplayViewModel
    {
        public int CompetenceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
        public IEnumerable<Realisation> LinkedRealisations { get; set; }

        public DisplayViewModel() { }

        public DisplayViewModel(Competence instance)
        {
            this.CompetenceId = instance.Id;
            this.Name = instance.Name;
            this.ImageName = instance.ImageName;
            this.Description = instance.Description;

            this.LinkedRealisations = new List<Realisation>();
        }
    }
}

Portfolio/ViewModels/Competences/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using ObjectModel.Competences;

namespace Portfolio.ViewModels.Competences
{
    /// <summary>
    /// ViewModel used to display a list of competences. (not in detail)
    /// </summary>
    public class ListViewModel
    {
        public IEnumerable<Competence> Competences { get; set; }

        public ListViewModel(IEnumerable<Competence> instance)
        {
            this.Competences = instance;
        }
    }
}

Portfolio/Controllers/CompetenceController.cs
using System.Web.Mvc;

using ObjectModel.Database;
using ObjectModel.Repositories;
using ObjectModel.Services;

using Portfolio.ViewModels.Competences;

namespace Portfolio.Controllers
{
    public class CompetenceController : BaseController
    {
        private RealisationAndCompetenceService _realAndCompService;

        public CompetenceController()
        {
            this._realAndCompService = new RealisationAndCompetenceService(new SMEntityRepository<ObjectModel.Database.Realisation, ObjectModel.Realisations.Realisation>(new SMPortfolioEntities()), new SMEntityRepository<ObjectModel.Database.Competence, ObjectModel.Competences.Competence>(new SMPortfolioEntities()));
        }

        public ActionResult Index()
        {
            var competenceList = _realAndCompService.GetAllCompetences();
            var model = new ListViewModel(competenceList);
            return View("Index", model);    
        }

        public ActionResult Detail(int id)
        {
            var competence = _realAndCompService.GetCompetenceById(id);

            if (competence == null)
                return View("404");

            var model = new DisplayViewModel(competence);
            model.LinkedRealisations = _realAndCompService.GetLinkedRealisations(competence.Id);

            return View("Detail", model);
        }
    }
}

Portfolio/Controllers/RealisationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ObjectModel.Services;
using ObjectModel.Repositories;
using ObjectModel.Database;

using Portfolio.ViewModels.Realisations;

namespace Portfolio.Controllers
{
    public class RealisationController : BaseController
    {
        private RealisationAndCompetenceService _realAndCompService;

        public RealisationController()
        {
            this._realAndCompService = new RealisationAndCompetenceService(new SMEntityRepository<ObjectModel.Database.Realisation, ObjectModel.Realisations.Realisation>(new SMPortfolioEntities()), new SMEntityRepository<ObjectModel.Database.Competence, ObjectModel.Competences.Competence>(new SMPortfolioEntities()));
        }

        public ActionResult Index()
        {
            var realisationList = _realAndCompService.GetAllRealisations();
            var model = new ListViewModel(realisationList);
            return View("Index", model);  
        }

        public ActionResult Detail(int id)
        {
            var realisation = _realAndCompService.GetRealisationById(id);

            if (realisation == null)
                return View("404");

            var model = new DisplayViewModel(realisation);
            model.LinkedCompetences = _realAndCompService.GetLinkedCompetences(realisation.Id);

            return View("Detail", model);
        }
    }
}

Portfolio/Views/Competence/Detail.cshtml
@{
    ViewBag.Title = "CompetenceDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Portfolio.ViewModels.Competences.DisplayViewModel

<h2>@Model.Name</h2>

<div class ="realisation-description">@Html.Raw(Model.Description)</div>
<img src="~/Content/img/logos/@Model.ImageName" class="realisation-logo" />

<div class="realisation-detail">
    <div class="competenceblock">
        <span>Réalisations associés :</span>
        <ul>
            @foreach (var real in Model.LinkedRealisations.OrderBy(p => p.Name))
            { 
                <li>@Html.ActionLink(real.Name, "Detail", "Realisation", new { id = real.Id }, null)</li>
            }
        </ul>
    </div>
</div>

Portfolio/Views/Competence/Index.cshtml
@{
    ViewBag.Title = "Mes compétences";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using ObjectModel.Competences
@using ObjectModel.Helpers
@model Portfolio.ViewModels.Competences.ListViewModel

<h2>Mes compétences</h2>

<div>
    @foreach (CompetenceType compType in Enum.GetValues(typeof(CompetenceType)))
    { 
        <h3>@EnumHelpers.GetResourceText(compType)</h3>
        foreach (var comp in Model.Competences.Where(p => p.Type == compType))
        {
            <div class="realisation-summary">
                <img src="~/Content/img/logos/@comp.ImageName" />
                <div>
                    <span class="realisationName">@comp.Name</span> @comp.ShortDescription
                    @Html.ActionLink(ObjectModel.Helpers.ResourceHelpers.GetString("General", "SEE_MORE"), "Detail", new { id = comp.Id })
                </div>
            </div>
        }
    }
</div>